- hosts: aws
  sudo: true
  user: ec2-user
  tasks:
    - yum: name=git
    - yum: name=vim
    - yum: name=golang
    #- get_url: url=https://dl.bintray.com/mitchellh/serf/0.6.3_linux_amd64.zip
    #  args:
    #    dest: /home/ec2-user
    #    mode: 0644
    #    sha256sum: 320a7811809210e91d4603c74e526fc34d5a59b06e913b68f45d92bd82a46800
    #- get_url: url=https://dl.bintray.com/mitchellh/consul/0.3.0_linux_amd64.zip
    #  args:
    #    dest: /home/ec2-user
    #    mode: 0644
    #    sha256sum: da1337ab3b236bad19b791a54a8df03a8c2a340500a392000c21608696957b15
    #- command: unzip 0.6.3_linux_amd64.zip creates=/home/ec2-user/serf
    #  args:
    #    chdir: /home/ec2-user
    #- command: unzip 0.3.0_linux_amd64.zip creates=/home/ec2-user/consul
    #  args:
    #    chdir: /home/ec2-user
    #- copy: src=~/.ssh/id_rsa dest=/home/ec2-user/.ssh/id_rsa
    - template: src=templates/ssh_config dest=/home/ec2-user/.ssh/config mode=0644
    - template: src=templates/bashrc dest=/home/ec2-user/.bashrc mode=0644

    #
    # git clone doesn't work well.
    # it works only for https protocol.
    #
    - git: repo=https://github.com/tmtk75/hoko dest=/home/ec2-user/hoko depth=1 update=yes
    #- git: repo=ssh://git@github.com/tmtk75/hoko dest=/home/ec2-user/hoko depth=1 update=yes
    #- file: path=/home/ec2-user/.go state=directory mode=0755
    #- command: go get -u github.com/tmtk75/hoko
    #  environment:
    #    GOPATH: /home/ec2-user/.go 

