- hosts: aws
  sudo: true
  user: ec2-user
  vars:
      home_dir: /home/ec2-user
  tasks:
    - yum: name=git
    - yum: name=vim
    - yum: name=golang
    - get_url: url=https://dl.bintray.com/mitchellh/serf/0.6.3_linux_amd64.zip
      args:
        dest: "{{ home_dir }}"
        mode: 0644
        sha256sum: 320a7811809210e91d4603c74e526fc34d5a59b06e913b68f45d92bd82a46800
    - get_url: url=https://dl.bintray.com/mitchellh/consul/0.3.0_linux_amd64.zip
      args:
        dest: "{{ home_dir }}"
        mode: 0644
        sha256sum: da1337ab3b236bad19b791a54a8df03a8c2a340500a392000c21608696957b15
    - command: unzip 0.6.3_linux_amd64.zip creates={{ home_dir }}/serf chdir={{ home_dir }}
    - command: unzip 0.3.0_linux_amd64.zip creates={{ home_dir }}/consul chdir={{ home_dir }}
    #- copy: src=~/.ssh/id_rsa dest=/home/ec2-user/.ssh/id_rsa
    - template: src=templates/ssh_config dest={{ home_dir }}/.ssh/config mode=0644
    - template: src=templates/bashrc dest={{ home_dir }}/.bashrc mode=0644

    #
    # git clone doesn't work well.
    # it works only for https protocol.
    #
    #- file: path={{ home_dir }}/.go/src/github.com/tmtk75 owner=ec2-user recurse=yes state=directory mode=0755
    - git: repo=https://github.com/tmtk75/hoko dest={{ home_dir }}/.go/src/github.com/tmtk75/hoko depth=1 update=yes
    - file: path={{ home_dir }}/hoko src={{ home_dir }}/.go/src/github.com/tmtk75/hoko owner=ec2-user state=link mode=0755
    #
    #- command: go get ./... chdir={{ home_dir }}/hoko
    #
    #- git: repo=ssh://git@github.com/tmtk75/hoko dest={{ home_dir }}/hoko depth=1 update=yes
    #- file: path={{ home_dir }}/.go state=directory mode=0755
    #- command: go get -u github.com/tmtk75/hoko
    #  environment:
    #    GOPATH: /home/ec2-user/.go 

