# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    branches:
      #only:
      #  - master
      #  - /[0-9]\.[0-9]\.[0-9]/
      ignore:
        - /dev-.*/
    docker:
      - image: circleci/golang:1.8

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/tmtk75/hoko
    steps:
      - checkout
      #- restore_cache:
      #    keys:
      #      - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "glide.yaml" }}
      - run: go get -v github.com/Masterminds/glide
      - run: go get github.com/mitchellh/gox
      - run: glide update
      - run: find ~/.glide
      #- save_cache:
      #    key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "glide.yaml" }}
      #    paths:
      #      - vendor
      - run: make build
      - run:
          name: test
          command: |
            mkdir -p test-reports
            go test -v . | tee ./test-reports/reports.txt
      - store_artifacts:
          path: test-reports/
          destination: tr1

#workflows:
#  version: 2
#  build_and_test:
#    jobs:
#      - build
#      - test:
#          requires:
#            - build
#          #filters:
#          #  branches:
#          #    only: circleci
