version: 2
jobs:
  build:
    branches:
      #only:
      #  - master
      #  - /[0-9]\.[0-9]\.[0-9]/
      ignore:
        - /dev-.*/

    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/tmtk75/hoko

    steps:
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Gopkg.lock" }}
      - run: go get github.com/golang/dep/cmd/dep
      - run: go get github.com/mitchellh/gox
      - run: go get github.com/tcnksm/ghr
      - run: dep ensure
      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - run: make build
      - run:
          name: test
          command: |
            mkdir -p test-reports
            go test -v . | tee ./test-reports/reports.txt
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_artifacts:
          path: pkg
          destination: nightly-build
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              rm -rf pkg/dist/hoko
              version=`git describe --tag`-${CIRCLE_BUILD_NUM}
              ghr -u tmtk75 ${version} pkg/dist
            fi

#workflows:
#  version: 2
#  build_and_test:
#    jobs:
#      - build
#      - test:
#          requires:
#            - build
#          #filters:
#          #  branches:
#          #    only: circleci
