version: 2
jobs:
  build:
    branches:
      #only:
      #  - master
      #  - /[0-9]\.[0-9]\.[0-9]/
      ignore:
        - /dev-.*/

    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/tmtk75/hoko

    steps:
      - checkout
      #- restore_cache:
      #    keys:
      #      - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "glide.yaml" }}
      #- run: go get -v github.com/Masterminds/glide
      - run: go get github.com/golang/dep/cmd/dep
      - run: go get github.com/mitchellh/gox
      - run: dep ensure
      #- save_cache:
      #    key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "glide.yaml" }}
      #    paths:
      #      - vendor
      - run: make build
      - run:
          name: test
          command: |
            mkdir -p test-reports
            go test -v . | tee ./test-reports/reports.txt
      - store_artifacts:
          path: test-reports/
          destination: tr1

#workflows:
#  version: 2
#  build_and_test:
#    jobs:
#      - build
#      - test:
#          requires:
#            - build
#          #filters:
#          #  branches:
#          #    only: circleci
