" Basic settings
set number
set nowrap

" Syntax highlighting
syntax enable
set nohlsearch
"set cursorline

" font thickness to be normal
hi Comment ctermfg=4
hi Identifier ctermfg=6
hi Constant ctermfg=5
hi LineNr ctermfg=3
hi Statement ctermfg=3
hi Special ctermfg=1
hi Type ctermfg=2

" Erasing previously entered characters in insert mode
" http://vim.wikia.com/wiki/Erasing_previously_entered_characters_in_insert_mode
set backspace=indent,eol,start

" Incremental search
set incsearch

" Complement mode
set wildmenu wildmode=list:full

" Status line
set laststatus=2
set statusline=%F\ %l,%c\ %r[%{&fenc}]


" Plugins with Vundle, see https://github.com/gmarik/Vundle.vim#quick-start
set nocompatible
filetype off 
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'fatih/vim-go'
Plugin 'https://github.com/mattn/emmet-vim'
call vundle#end()
filetype plugin indent on

" vim-go, see https://github.com/fatih/vim-go
"let g:go_fmt_autosave = 0


" emmet-vim
let g:user_emmet_install_global = 0
autocmd FileType html,css EmmetInstall


" Indent
set autoindent
"au BufNewFile,BufRead *.go set noexpandtab tabstop=8 shiftwidth=8
au BufNewFile,BufRead *.rb set expandtab tabstop=2 shiftwidth=2
au BufNewFile,BufRead *.js set expandtab tabstop=2 shiftwidth=2
au BufNewFile,BufRead *.html set expandtab tabstop=4 shiftwidth=4
au BufNewFile,BufRead *.css set expandtab tabstop=4 shiftwidth=4


" clipboard
"set clipboard+=unnamed


"---- old setings ----
" gocode
"filetype plugin indent on
"
"call pathogen#incubate()
"call pathogen#infect('bundle/{}')
"
"set expandtab
"set tabstop=4
"set ruler
"set autoindent
"set shiftwidth=2
"
"set encoding=utf-8
""set fileencodings=ucs-bom,iso-2022-jp-3,iso-2022-jp,eucjp-ms,euc-jisx0213,euc-jp,sjis,cp932,utf-8
"set fileencodings=utf-8
"set laststatus=2
"set statusline=%<%f\ %m%r%h%w%{'['.(&fenc!=''?&fenc:&enc).']['.&ff.']'}%=%l,%c%V%8P
"set fileformat=unix
""set fileformat=dos
""set fileformat=mac
"
"set noequalalways
""set noautoindent
"set winheight=8
"set winwidth=80
"
"if has('path_extra')
"  set tags+=.tags;
"endif
"
"hi Pmenu ctermbg=0
"hi PmenuSel ctermbg=4
"hi PmenuSbar ctermbg=2
"hi PmenuThumb ctermfg=3
"
"set rtp+=/usr/local/Cellar/go/1.2/libexec/misc/vim
"exe "set rtp+=".globpath($GOPATH, "src/github.com/nsf/gocode/vim")
"runtime! ftdetect/*.vim
"set completeopt=menu,preview
"
"set nocompatible
"filetype plugin on
"runtime macros/matchit.vim

